<style>
    *{
        font-family: Arial,sans-serif;
    }
    form div{
        padding: 3px;
    }
    label{
        display: inline-block;
        width: 180px;
        text-align: right;
        padding-right: 5px;
        font-size: 12px;
    }
</style>

<h2>Test REST API and make sure a workspace is sync-ready.</h2>

<form method="post" target="test-result">

    <div><label for="user">Protocol</label><input name="protocol" value="<?php print($protocol); ?>" id="protocol" type="text"></div>
    <div><label for="user">Host</label><input name="host" id="host" value="<?php print($host); ?>" type="text"></div>
    <div><label for="user">Path</label><input name="path" id="path" value="<?php print($path); ?>" type="text"></div>
    <div><label for="ws-alias">Workspace Alias (slug)</label><input name="ws-alias" id="ws-alias" type="text"></div>

    <div style="margin-top: 10px;"><label for="user">User</label><input name="user" id="user" type="text"></div>
    <div><label for="password">Password</label><input name="password" id="password" type="password"></div>


    <input type="submit" value="Test API!">

</form>


<iframe name="test-result" src="" id="test-result" style="width: 100%; height: 65%;"></iframe>