<?php
// $Id$
define('AJXP_EXEC', true);

function pydio_help($path, $arg){
  $output = '';  //declare your output variable
  switch ($path) {
    case "admin/help#ajaxplorer":
      $output = '<p>'.  t("Will create a bridge between drupal and Pydio users.") .'</p>';
      break;
  }
  return $output;
}

function pydio_permission(){
  return array(
    'administer ajaxplorer' => array(
      'title' => t('Administer Pydio repositories'),
    ),
  );
}

function pydio_user_login(&$edit, $account){
    pydio_user_func("login", $edit, $account);
}

function pydio_user_logout($account){
    $empty = "";
    pydio_user_func("logout", $empty, $account);
}

function pydio_user_insert(&$edit, $account){
    pydio_user_func("insert", $edit, $account);
}
function pydio_user_update(&$edit, $account){
    pydio_user_func("update", $edit, $account);
}
function pydio_user_delete($account){
    $empty = "";
    pydio_user_func("delete", $empty, $account);
}


function pydio_map_roles($role) {
    return user_role_load($role)->name;
}

function pydio_user_func($op, &$edit, $account, $category = null){
	require_once("class.DrupalPydio.php");
 	$params = array(
        	"ajxp_install_path" => variable_get('pydio_install_path', ""),
        	"ajxp_secret_key" => variable_get('pydio_secret_key', ""),
			"ajxp_auto_create" => (variable_get('pydio_auto_create', "0") == "0"?true:false)
    );
	$drupHandler = new DrupalPydio($params);

        $roles = array_map("pydio_map_roles", array_keys($account->roles));

	if(!$drupHandler->glueCodeFound) return ;
	switch ($op) {
		case "login":
			$drupHandler->onLoginUser($edit["input"]["name"], $edit["input"]["pass"], $roles);
			break;
	
		case "logout":
			$drupHandler->onLogout($account);
			break;
			
		case "insert":
			$result = $drupHandler->onAfterStoreUser($account->name, $account->pass, $roles, true);
			break;

		case "update":
			$result = $drupHandler->onAfterStoreUser($account->name, $account->pass, $roles, false);
			break;

		case "delete":
			$drupHandler->onAfterDeleteUser($account->name);
			break;
	
		default:
			break;
	}
	
}

function pydio_menu() {

  $items = array();

  $items['admin/settings/ajaxplorer'] = array(
    'title' => 'Pydio Settings',
    'description' => 'Pydio bridge settings, it is necessary to fill them to make this module work.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pydio_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}

function pydio_admin() {
  $form = array();

  $form['pydio_install_path'] = array(
    '#type' => 'textfield',
    '#title' => t('Pydio Install Path'),
    '#default_value' => variable_get('pydio_install_path', ""),
    '#size' => 50,
    '#description' => t("Absolute path to the root folder of your Pydio installation, the one containing the index.php file. <b>No trailing slash at the end.</b>"),
    '#required' => TRUE,
  );

  $form['pydio_secret_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Secret Key'),
    '#default_value' => variable_get('pydio_secret_key', ""),
    '#size' => 50,
    '#description' => t("Must be the same string as the one found in your AUTH_DRIVER configuration of Pydio."),
    '#required' => TRUE,
  );

  $form['pydio_auto_create'] = array(
    '#type' => 'radios',
    '#title' => t('Auto Create'),
    '#default_value' => variable_get('pydio_auto_create', 0),
    '#options' => array("True", "False"),
    '#description' => t("Whether the user will be created automatically at login time (true), or if they must be created before (false)"),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}
